name: Hadoop Base Release

on:
  workflow_dispatch:
    inputs:
      hadoop_version:
        description: 'Haddoop version to build the image on'
        required: true
        default: '3.3.3'

jobs:
  'hadoop-base':
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/clinia/hadoop-base
          HADOOP_VERSION=${{ github.event.inputs.version }}
          TAGS="${DOCKER_IMAGE}:hadoop${HADOOP_VERSION}-java8"

          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ghcr_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          context: base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}